src/components/IIIFPlayer/IIIFPlayer.js, src/components/IIIFPlayer/IIIFPlayer.md, src/components/IIIFPlayerWrapper.js, src/json/volleyball-for-boys-video.js
Provide a manifest and manifestUrl to verify that manifest takes precedence.
Closes #23
=> Add support for manifest prop

package.json, src/components/List.js, src/components/ListItem.js, src/components/StructuredNavigation/StructuredNavigation.md, src/components/StructuredNavigation/StructuredNavigation.scss, src/styles/_vars.scss, src/styles/main.scss
This is a partial PR, but I know others are working on potential styling UI so wanted to get this in as an example of how we can structure styling in the app.
References this color chart:
https://www.schemecolor.com/20-best-gray-colors-for-ui-web-design.php
=> Add Scss pattern

package.json, src/components/IIIFPlayer/IIIFPlayer.md, src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/MediaPlayer.test.js, src/components/MediaPlayer/VideoJSPlayer.js, yarn.lock
This is pretty similar to @Dananji 's branch, just with a few more events wired up.   If people are comfortable with it, we could merge it into `main` and just do away with MediaElement.js.
=> VideoJS initial wire up

package.json, src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/VideoJSPlayer.js, src/context/player-context.js, yarn.lock
=> Highlight timefragment on player

src/components/ListItem.js, src/components/StructuredNavigation/StructuredNavigation.scss, src/styles/_vars.scss
=> Indicate active structured navigation

src/components/IIIFPlayer/IIIFPlayer.md, src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/VideoJSPlayer.js, src/components/MediaPlayer/vjsYo.js
Another partial PR, but this basically takes the React integration example VideoJS provides (https://docs.videojs.com/tutorial-react.html), and puts it into place in our app.
It's just a step 1 to figure out how they're doing it using `ReactDOM` from what it looks like.
The following steps would be good to pursue:
1. Convert this functionality away from `Class` based functions so we can use Hooks?
2. Figure out how to place these new components inside the Providers so we can access and dispatch to Provider data.  Seems like they're kind of living on their own now?  Not sure where they're even at in the scope of the React project.
=> Example of how to add a custom control as a Class to the player

src/components/IIIFPlayer/IIIFPlayer.md, src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/VideoJSPlayer.js, src/context/player-context.js, src/json/multiple-sources.js, src/services/iiif-parser.js, src/styles/main.scss
This PR contains the following;
1. Handle source transition between same source types (audio/video) for `ended` event from the VideoJS player
2. Structure navigation across same source types (audio/video)
=> Structure nav

src/components/IIIFPlayer/IIIFPlayer.md, src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/VideoJSPlayer.js
Minor updates to player sizing
=> Make audio player smaller, and player responsive

src/components/ListItem.js, src/components/MediaPlayer/VideoJSPlayer.js, src/components/StructuredNavigation/StructuredNavigation.scss
=> Fix playhead z-index and marker tooltip text

src/components/MediaPlayer/VideoJSPlayer.js, src/styles/main.scss
=> Update markers styling

src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/VideoJSPlayer.js
=> Fix for failing navigation when same item is clicked twice

.circleci/config.yml, yarn.lock
Fixes many of the security vulnerabilities.
=> Bump dependencies

src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/VideoJSComponents/js/VideoJSNextButton.js, src/components/MediaPlayer/VideoJSComponents/js/VideoJSPreviousButton.js, src/components/MediaPlayer/VideoJSPlayer.js
Bug fix for switching between canvases using previous/next buttons to update start time of the player
=> Fix bug when switching canvas using previous/next buttons

README.md, demo/config.js, public/dev/lunchroom_manners.json
Changes to the code and README after adding ramp.avalonmediasystem.org as a domain for the Netlify site.
Closes #162
=> Fix prod data manifests to work with multiple domain names

src/components/MediaPlayer/VideoJS/components/js/VideoJSFileDownload.js
Fix for file download icon with the changed parsing implemented in the SupplementalFiles component.
=> Fix VideoJS file download bug

src/components/StructuredNavigation/StructuredNavigation.scss, src/styles/_vars.scss
Closes #181 
In StructuredNavigation:
In Transcript:
=> Fix color contrast in links

src/components/IIIFPlayerWrapper.js, src/components/MarkersDisplay/MarkersDisplay.test.js, src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/MediaPlayer.scss, src/components/MediaPlayer/MediaPlayer.test.js, src/components/MediaPlayer/VideoJS/VideoJSPlayer.js, src/components/StructuredNavigation/NavUtils/ListItem.js, src/components/StructuredNavigation/NavUtils/ListItem.test.js, src/components/StructuredNavigation/StructuredNavigation.js, src/components/StructuredNavigation/StructuredNavigation.scss, src/components/StructuredNavigation/StructuredNavigation.test.js, src/context/manifest-context.js, src/services/iiif-parser.js, src/services/iiif-parser.test.js, src/services/transcript-parser.js, src/services/utility-helpers.js, src/services/utility-helpers.test.js, src/test_data/lunchroom-manners.js, src/test_data/playlist.js, src/test_data/transcript-annotation.js
=> Add handling for empty canvases within playlist manifests

src/components/StructuredNavigation/StructuredNavigation.scss
=> Fix color contrast for links when hovered

src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
=> Player respects auto advance toggle

src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/VideoJS/VideoJSPlayer.js, src/styles/main.scss
=> Make the volume slider horizontal and sticky for audio player

src/components/StructuredNavigation/NavUtils/List.test.js, src/components/StructuredNavigation/NavUtils/ListItem.js, src/components/StructuredNavigation/NavUtils/ListItem.test.js, src/components/StructuredNavigation/NavUtils/SectionHeading.js, src/components/StructuredNavigation/NavUtils/SectionHeading.test.js, src/components/StructuredNavigation/StructuredNavigation.scss
Mark active section when there are;
Canvas with child timespans:
Canvas without child timespans:
Canvas without children (timespans/divs):
=> Add active section

demo/app.scss, package.json, src/components/ErrorMessage/ErrorMessage.js, src/components/ErrorMessage/ErrorMessage.scss, src/components/IIIFPlayer/IIIFPlayer.js, src/components/IIIFPlayer/IIIFPlayer.md, src/components/IIIFPlayerWrapper.js, src/components/MarkersDisplay/MarkerUtils/CreateMarker.js, src/components/MarkersDisplay/MarkerUtils/MarkerRow.js, src/components/MarkersDisplay/MarkersDisplay.js, src/components/MarkersDisplay/MarkersDisplay.test.js, src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/MediaPlayer.test.js, src/components/MetadataDisplay/MetadataDisplay.test.js, src/components/StructuredNavigation/NavUtils/SectionHeading.js, src/components/StructuredNavigation/StructuredNavigation.js, src/components/StructuredNavigation/StructuredNavigation.test.js, src/components/SupplementalFiles/SupplementalFiles.js, src/components/SupplementalFiles/SupplementalFiles.test.js, src/components/Transcript/Transcript.test.js, src/services/iiif-parser.js, src/services/iiif-parser.test.js, src/services/playlist-parser.js, src/services/transcript-parser.js, src/services/transcript-parser.test.js, src/services/utility-helpers.js, src/test_data/volleyball-for-boys.js, yarn.lock
Default message;
Custom message (using new prop `customErrorMessage`);
=> Error boundary

src/components/StructuredNavigation/NavUtils/List.test.js, src/components/StructuredNavigation/NavUtils/ListItem.js, src/components/StructuredNavigation/NavUtils/ListItem.test.js
=> Display tracker when displaying playlist manifests

demo/app.js
[tab-nav.webm](https://github.com/samvera-labs/ramp/assets/1331659/3a75322a-195d-4e3d-bfec-449705cfd460)
=> Fix keyboard navigation for the tabbed view in demo site

src/components/StructuredNavigation/NavUtils/List.js, src/components/StructuredNavigation/NavUtils/List.test.js, src/components/StructuredNavigation/NavUtils/ListItem.js, src/components/StructuredNavigation/NavUtils/ListItem.test.js, src/components/StructuredNavigation/StructuredNavigation.js
[structure-scroll.webm](https://github.com/samvera-labs/ramp/assets/1331659/0d9de031-820a-4100-b924-9c2c1c51570f)
=> Scroll active structure item into view within the component

src/components/Transcript/Transcript.js, src/components/Transcript/Transcript.md, src/components/Transcript/Transcript.test.js, src/services/transcript-parser.js, src/services/transcript-parser.test.js
=> Display a message for unsupported transcript file formats

src/components/IIIFPlayerWrapper.js
=> Show generic error message when manifest request fails

src/components/IIIFPlayer/IIIFPlayer.js, src/components/IIIFPlayer/IIIFPlayer.md, src/components/IIIFPlayerWrapper.js, src/components/StructuredNavigation/StructuredNavigation.js, src/services/iiif-parser.js, src/services/iiif-parser.test.js, src/test_data/empty-manifest.js
Updated Wiki: https://github.com/samvera-labs/ramp/wiki/IIIFPlayer-Component
=> Add 2 new props to set start canvas and time, and map them to start property behavior from a IIIF Manifest

src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/VideoJS/VideoJSPlayer.js, src/components/MediaPlayer/VideoJS/components/js/VideoJSTrackScrubber.js, src/components/MediaPlayer/VideoJS/components/styles/VideoJSProgress.scss, src/components/MediaPlayer/VideoJS/components/styles/VideoJSTrackScrubber.scss, src/context/manifest-context.js, src/services/utility-helpers.js, src/styles/main.scss
[Track scrubber with auto-advance.webm](https://github.com/samvera-labs/ramp/assets/1331659/8210e5a6-8d23-4ca9-b016-532163ae8574)
[Track scrubber with track switching.webm](https://github.com/samvera-labs/ramp/assets/1331659/6e7d55e9-8b45-480e-8456-52f09c5bb1df)
=> Track scrubber

src/components/MediaPlayer/VideoJS/components/js/VideoJSCurrentTime.js, src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
Fixes [Avalon #5434](https://github.com/avalonmediasystem/avalon/issues/5434)
=> Disable update of custom timer and progress bar in iOS context

src/components/MarkersDisplay/MarkersDisplay.js, src/components/MarkersDisplay/MarkersDisplay.test.js, src/services/playlist-parser.js, src/services/playlist-parser.test.js
Issue: https://github.com/samvera-labs/ramp/issues/303
=> Remove no markers message in MarkersDisplay component

src/services/utility-helpers.js
Could be related to https://github.com/avalonmediasystem/avalon/issues/5585 ?
=> Fix breaking hotkeys after switching Canvas

src/components/MediaPlayer/VideoJS/components/js/VideoJSCurrentTime.js, src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
Related issue: https://github.com/samvera-labs/ramp/issues/338
=> Fix playback issues in Safari

src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/MediaPlayer.test.js, src/components/MediaPlayer/VideoJS/components/js/VideoJSNextButton.js
Related issue: https://github.com/samvera-labs/ramp/issues/349
=> Fix next Canvas button click

src/components/Transcript/Transcript.js
Related issue: https://github.com/avalonmediasystem/avalon/issues/5584
=> Display transcript content on first load

src/components/StructuredNavigation/StructuredNavigation.scss
Related issue: https://github.com/avalonmediasystem/avalon/issues/5589
=> Make CSS for scrolling in structure work with adjustable height in host apps

src/components/SupplementalFiles/SupplementalFiles.js, src/components/SupplementalFiles/SupplementalFiles.test.js, src/components/Transcript/Transcript.js, src/components/Transcript/TranscriptMenu/TranscriptSelector.js, src/services/iiif-parser.js, src/services/transcript-parser.js, src/services/transcript-parser.test.js, src/services/utility-helpers.js, src/services/utility-helpers.test.js
=> Improve handling of download filenames in Transcript and Supplemental File components

src/components/Transcript/Transcript.js
=> Give transcript items "role=listitem" attribute

src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/VideoJS/VideoJSPlayer.js, src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js, src/components/Transcript/TranscriptMenu/TranscriptSelector.js
Related issue: https://github.com/samvera-labs/ramp/issues/325
=> Override Safari's native text track functionality

src/components/StructuredNavigation/StructuredNavigation.scss
Related issue: https://github.com/avalonmediasystem/avalon/issues/5589
=> Stick scroll to see more text into one line

src/components/MediaPlayer/MediaPlayer.js, src/services/browser.js, src/services/iiif-parser.js, src/services/iiif-parser.test.js, src/services/utility-helpers.js, src/services/utility-helpers.test.js, src/test_data/transcript-multiple-canvas.js
=> Show captions in native player in iOS

src/services/utility-helpers.js, src/services/utility-helpers.test.js
=> Use caption label in menu, not filename

src/components/StructuredNavigation/NavUtils/ListItem.js, src/components/StructuredNavigation/NavUtils/SectionHeading.js
=> Fix active structure items blinking with user interactions

src/components/StructuredNavigation/StructuredNavigation.js, src/components/StructuredNavigation/StructuredNavigation.test.js
Related issue: avalonmediasystem/avalon#5716
=> Update 'Scroll for More' message when StuctNav is resized

src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
=> Remove track.off('change') for unknown cc in iOS context

public/manifests/dev/lunchroom_manners.json, public/manifests/prod/lunchroom_manners.json, src/components/StructuredNavigation/NavUtils/List.test.js, src/components/StructuredNavigation/NavUtils/ListItem.js, src/components/StructuredNavigation/NavUtils/ListItem.test.js, src/services/iiif-parser.js, src/services/iiif-parser.test.js, src/services/utility-helpers.js
=> Display timespans past duration as links in StructuredNavigation

src/components/Transcript/Transcript.js, src/services/utility-helpers.js
Related issue: https://github.com/avalonmediasystem/avalon/issues/5609
https://github.com/samvera-labs/ramp/assets/1331659/55757a7c-e5c3-4d3b-920c-5b98c0742239
=> Auto scroll active transcript cue to the top

demo/app.js, src/components/MetadataDisplay/MetadataDisplay.js, src/components/StructuredNavigation/NavUtils/List.js, src/components/StructuredNavigation/NavUtils/ListItem.js, src/components/StructuredNavigation/NavUtils/SectionHeading.js, src/components/StructuredNavigation/StructuredNavigation.js, src/services/utility-helpers.js
=> Improve structured navigation user experience

src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
Follow-up on suggested changes in https://github.com/samvera-labs/ramp/pull/460#discussion_r1576531153, fix CSS for placeholder canvas messages with links, and cleanup unnecessary code left from https://github.com/samvera-labs/ramp/pull/460.
=> Remove CSS classes for captions, fix CSS for placeholder canvas messages

src/services/search.js
=> Handle case when some transcripts have hits but others do not

src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/VideoJS/VideoJSPlayer.js, src/styles/main.scss
Related issue: #525 
The adjusted icon width and font-size in Ramp player in Avalon:
=> Mobile icons

src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
=> Preserve captions off state in native iOS player on play event

src/components/Transcript/Transcript.js
=> Scroll transcript search hits within container

src/components/Transcript/Transcript.test.js, src/components/Transcript/TranscriptMenu/TranscriptMenu.js, src/components/Transcript/TranscriptMenu/TranscriptMenu.scss, src/components/Transcript/TranscriptMenu/TranscriptSelector.js, src/components/Transcript/TranscriptMenu/TranscriptSelector.test.js
=> Use flexbox instead of grid to arrange transcript menu

src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
=> Remember active caption selection

src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
Related issue and comment: https://github.com/samvera-labs/ramp/issues/473, https://github.com/samvera-labs/ramp/issues/473#issuecomment-2214505396
=> Fix for multiple captions being selected in captions menu

src/components/MarkersDisplay/MarkersDisplay.test.js, src/components/MediaPlayer/MediaPlayer.test.js, src/components/MediaPlayer/VideoJS/VideoJSPlayer.js, src/components/MetadataDisplay/MetadataDisplay.test.js, src/components/StructuredNavigation/StructuredNavigation.test.js, src/services/iiif-parser.test.js, src/services/playlist-parser.test.js, src/test_data/playlist.js
=> Fix prev/next button bugs in mobile devices

src/components/Transcript/TranscriptMenu/TranscriptSearch.js, src/components/Transcript/TranscriptMenu/TranscriptSearch.test.js
Related issue: avalonmediasystem/avalon#5903
=> Update no results message in transcript search

src/components/StructuredNavigation/StructuredNavigation.js
=> Ensure autoplay of next section when selecting inaccesible item

src/services/transcript-parser.js, src/services/transcript-parser.test.js
=> Fix split query bug in altReplace func

src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
=> Update canvas duration on ready event

src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
=> Allow progress bar updates with playback for audio in iOS

src/components/MediaPlayer/VideoJS/components/js/VideoJSCurrentTime.js
Related issue: #582
Missed this when working on progress updates issue for audio player in iOS.
=> Update current time in audio player in iOS context

src/components/MediaPlayer/VideoJS/components/js/VideoJSCurrentTime.js, src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
=> Improve scrubbing in Safari with throttle and debounce on update events

src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
=> Bug fix in desktop Safari scrubbing introduced in #597

src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
=> Use targetTouches in touch event to calculate progress updates

src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
=> Force the media to load for iOS and Safari on desktop

src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
=> Fix broken captions button reference in handleCaptionChange()

src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js, src/services/iiif-parser.js, src/services/iiif-parser.test.js
=> Start from custom manifest start

src/components/MediaPlayer/MediaPlayer.js
=> Default to empty string if manifest label is not present

src/components/MediaPlayer/MediaPlayer.test.js, src/components/MediaPlayer/VideoJS/VideoJSPlayer.js, src/services/local-storage.js
Related issue: https://github.com/avalonmediasystem/avalon/issues/5651
=> Store captions on/off status in localstorage for session

CHANGELOG.md, package.json, src/components/MediaPlayer/MediaPlayer.js, src/components/MediaPlayer/VideoJS/VideoJSPlayer.js, src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
Changes from 3.2.1 to include overwritten changes in https://github.com/samvera-labs/ramp/pull/594 during conflict resolution.
=> 3.2.1 patch

src/styles/main.scss
Related issue: #658 
https://github.com/user-attachments/assets/c150c816-7338-4e2e-8740-f396ab7ed655
=> Move captions above controls when user is active

src/components/MediaPlayer/VideoJS/videojs-theme.scss
Related issue: https://github.com/samvera-labs/ramp/issues/676
=> Change min-width and min-height of the player for iOS

src/components/MediaPlayer/VideoJS/videojs-theme.scss
Related issue: #676 for Android
=> Extend player min-width to Android browsers

src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
=> Prevent playhead from jumping to end of progress bar

src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
Related issue: #701 
Update played range for mobile devices in the timeupdate handler, this helpful with updating progress-bar when the user is structured navigation.
NOTE: I was seeing laggy updates for the same steps in Safari in desktop, which was not reported in the ticket. 
To solve this, I removed the abortable time-update handler we were using in the progress-bar. This is part of the previous implementation where, we built the progress-bar from scratch. 
It seems with the refactor of the progress-bar component to use VideoJS' native component solved the issue we were trying to solve with the abortable time-update handler (laggy time-updates and jumping back and forth when scrubbing/seeking in Safari browsers). 
In my initial testing during development, I was not seeing any issues …
=> Explicitly update played range 

src/context/manifest-context.js, src/services/annotation-parser.test.js, src/services/annotations-parser.js, src/services/utility-helpers.js
=> Annotation parser

src/components/StructuredNavigation/NavUtils/SectionHeading.js, src/components/StructuredNavigation/NavUtils/SectionHeading.test.js, src/services/ramp-hooks.js
=> Scroll active section into view when playback is started

src/components/Transcript/Transcript.js, src/components/Transcript/Transcript.scss, src/components/Transcript/Transcript.test.js, src/services/utility-helpers.js
=> A11y transcript cues

src/components/MarkersDisplay/MarkersDisplay.js
Related issue: https://github.com/avalonmediasystem/avalon/issues/6184
=> Check for annotations before rendering AnnotationsDisplay

src/components/MarkersDisplay/Annotations/AnnotationRow.js, src/components/MarkersDisplay/Annotations/AnnotationRow.test.js, src/components/MarkersDisplay/MarkersDisplay.scss
=> Fix display of longer list of tags with show/hide more button

docs/manifests/dev/volleyball-for-boys.json, public/manifests/dev/volleyball-for-boys.json, src/components/MarkersDisplay/Annotations/AnnotationRow.js, src/components/MarkersDisplay/Annotations/AnnotationRow.test.js, src/components/MarkersDisplay/Annotations/AnnotationSetSelect.js, src/components/MarkersDisplay/Annotations/AnnotationsDisplay.js, src/components/MarkersDisplay/Annotations/AnnotationsDisplay.test.js, src/components/MarkersDisplay/MarkerUtils/CreateMarker.js, src/components/MarkersDisplay/MarkersDisplay.js, src/components/MarkersDisplay/MarkersDisplay.test.js, src/components/Transcript/Transcript.test.js, src/context/manifest-context.js, src/services/annotation-parser.test.js, src/services/annotations-parser.js, src/services/playlist-parser.js, src/services/playlist-parser.test.js, src/services/ramp-hooks.js, src/services/ramp-hooks.test.js, src/services/transcript-parser.js, src/services/transcript-parser.test.js, src/test_data/lunchroom-manners.js, src/test_data/transcript-multiple-canvas.js
=> Annotation cleanup

src/components/MarkersDisplay/Annotations/AnnotationRow.js, src/context/manifest-context.js, src/services/ramp-hooks.js
Related issue: #764 and https://github.com/samvera-labs/ramp/issues/764#issuecomment-2749165833
=> Scroll to clicked annotation when there's multiple annotations in range

.circleci/config.yml
From https://github.com/avalonmediasystem/react-structural-metadata-editor/pull/226 by @cjcolvar
=> Copy over latest CircleCI config from SME

src/components/MarkersDisplay/Annotations/AnnotationSetSelect.js, src/components/MarkersDisplay/Annotations/AnnotationSetSelect.test.js
=> Add event listener for click outside event to close annotations dropdown

src/components/IIIFPlayer/IIIFPlayer.js, src/services/iiif-parser.test.js
=> Handle manifest w/o items error in ErrorBoundary

src/components/MarkersDisplay/Annotations/AnnotationRow.js, src/components/MarkersDisplay/Annotations/AnnotationRow.test.js
=> Scroll annotation into view when show less is clicked

src/components/AutoAdvanceToggle/AutoAdvanceToggle.js, src/components/AutoAdvanceToggle/AutoAdvanceToggle.scss, src/components/AutoAdvanceToggle/AutoAdvanceToggle.test.js, src/services/utility-helpers.js
Related issue: #796 
Adapted accessibility design pattern: https://www.w3.org/WAI/ARIA/apg/patterns/switch/examples/switch-button/
=> Enable enter/space key activation for toggle button

demo/app.js, src/components/StructuredNavigation/StructuredNavigation.js
=> Fix double focus in structure and tabbed UI elements

src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
Related issue: https://github.com/avalonmediasystem/avalon/issues/6264
=> Handle sequential time updates in seek using setTimeout

src/components/StructuredNavigation/StructuredNavigation.js
=> Fix double focus in strucutred nav on initial Shift+Tab

src/components/Transcript/Transcript.js
Change transcript roles to fix role relationship error in SiteImprove when using `role="list"` on parent container while each cue is being presented with a `role="button"`.
In addition, add an `aria-label` for each cue with a more user friendly time format for screen readers to use.
=> Change role relationship in transcript cues

src/components/Transcript/TranscriptMenu/TranscriptSelector.test.js, src/services/annotations-parser.js, src/services/ramp-hooks.js, src/services/search-parser.js, src/services/transcript-parser.js, src/services/transcript-parser.test.js, src/test_data/multi-source-manifest.js
=> Display inline supplementing annotations in transcript component
