- src/components/ListItem.js
- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJSPlayer.js
- src/json/multiple-sources.js
- src/services/iiif-parser.js
This PR includes;
1. Bug fix for when switching audio -> video player with play() event
2. Marking the current nav item when advancing from canvas to next when the current media ends playing
> Bug fixes when switching the player

- demo/app.js
- src/components/AutoAdvanceToggle/AutoAdvanceToggle.js
- src/components/AutoAdvanceToggle/AutoAdvanceToggle.md
- src/components/AutoAdvanceToggle/AutoAdvanceToggle.scss
- src/components/AutoAdvanceToggle/AutoAdvanceToggle.test.js
- src/components/IIIFPlayerWrapper.js
- src/components/MediaPlayer/MediaPlayer.js
- src/context/manifest-context.js
- src/main.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/test_data/multiple-canvas-auto-advance.js
> Add top level auto-advance toggle component.

- demo/app.js
- demo/index.js
- public/manifests/dev/lunchroom_manners.json
- public/manifests/dev/playlist-manifest.json
- public/manifests/playlist.js
- src/components/IIIFPlayerWrapper.js
- src/components/MarkersDisplay/MarkersDisplay.js
- src/components/MarkersDisplay/MarkersDisplay.md
- src/components/MarkersDisplay/MarkersDisplay.scss
- src/components/MarkersDisplay/MarkersDisplay.test.js
- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/MediaPlayer.test.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
- src/components/Transcript/Transcript.js
- src/context/manifest-context.js
- src/main.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/services/utility-helpers.js
- src/services/utility-helpers.test.js
- src/test_data/playlist.js
Markers display:
Marker edit form:
Marker delete:
No markers in Canvas:
Closes #212
> Markers firstpass

- src/components/MediaPlayer/VideoJS/components/styles/VideoJSProgress.scss
Before:
With the time tooltip on top of the time rail, scrubbing doesn't work because the progress bar doesn't register the mouse click event.
After:
> Fix broken scrubbing due to time tooltip styling

- src/services/iiif-parser.js
- src/test_data/lunchroom-manners.js
[The behavior encountered](https://github.com/avalonmediasystem/avalon/issues/5350) by Avalon with Ramp components not loading was because of top level ranges having an empty item section: `item: [ ]`. The parser would attempt to grab the item's ID and the parsing would fail, causing all of the components to stop processing.
This PR adds a condition to check the length of the item array before grabbing the ID value.
> Add check for empty item to getItemId

- demo/app.scss
The issue with icons in the control bar we were seeing when zooming-in was happening only in the demo site, because it sets the player width to 60%. The issue was not with VideoJS CSS. Example screenshots below where the player's width is not adjusted show the full control bar at 240% zoom level in the browser. 
GitHub documentation site:
avalon-dev:
> Fix player css for zooming in demo site

- src/services/iiif-parser.js
Without this change manifests like https://avalon-dev.dlib.indiana.edu/playlists/32/manifest.json would log an error message to the console but not sure if it actually broke anything.
> Handle case when range only has a single canvas child

- README.md
- package.json
- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- yarn.lock
Videojs-hotkeys was not interfacing correctly between Avalon and embedded Ramp. This could be an issue encountered by other implementers. Rather than cobble together a fix on the Avalon side and documenting that for others, it felt better to try to change the approach in Ramp so that hopefully workarounds would not be necessary. 
To that end, recent versions of VideoJS have added a builtin hotkey ability so we are going to try switching to that. This currently requires building the hotkeys out from scratch because the defaults do not include all of the functionality we require and adding any customization disables the defaults. It may be worthwhile exploring contributing "seek" and "volume" hotkey components back upstream to be added to the VideoJS default behaviors but that is a future …
> Replace videojs-hotkeys with builtin hotkeys function

- src/components/IIIFPlayerWrapper.js
- src/components/MarkersDisplay/MarkerUtils/CreateMarker.js
- src/components/MarkersDisplay/MarkerUtils/MarkerRow.js
Cookbook recipes or any other external manifests don't open in the demo site with the `Avalon-Api-Key` in the header of the manifest request. This PR remove it from the header fields.
> Remove Avalon-Api-Key field from request

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSCurrentTime.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
This PR also includes a commit that removes videojs-hotkeys initialization code that was accidentally reintroduced after we stopped using that plugin.
> Prevent retrieving currentTime when player is disposed

- src/components/StructuredNavigation/StructuredNavigation.scss
> Fix mismatching colors for button and span section items in structure

- src/services/iiif-parser.js
0 evaluates as falsy in javascript, so we need to explictly check for it in our if/else check when grabbing canvasindex.
> Fix missing canvas console error

- src/styles/main.scss
This change is made in the main.scss file because the override defines a custom scrollbar design. If we were to limit this CSS to only one component (StructuredNavigation) the rest of the components would use the browser default scroll bar which may not match the styling defined here. For visual consistency within Ramp, we need to apply the scrollbar rule to all scrollbars in the application.
> Add scrollbar override to enable constant display

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/MediaPlayer.scss
- src/components/MediaPlayer/MediaPlayer.test.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSCurrentTime.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
- src/components/StructuredNavigation/StructuredNavigation.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/test_data/transcript-annotation.js
> Display placeholder canvas message for all empty manifests

- public/manifests/dev/lunchroom_manners.json
- public/manifests/prod/lunchroom_manners.json
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/StructuredNavigation/NavUtils/ListItem.js
- src/components/StructuredNavigation/StructuredNavigation.js
- src/components/StructuredNavigation/StructuredNavigation.test.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/test_data/lunchroom-manners.js
When playhead is at a timestamp not included in a timespan in the structure:
When playhead is at a timestamp included in a timespan in the structure:
> Fix structure display for section items with Canvas references

- demo/app.js
- demo/app.scss
Re-implemented the tabs in compliance with the tabs pattern in W3C guide: https://www.w3.org/WAI/ARIA/apg/patterns/tabs/
Blog followed: https://www.w3.org/WAI/ARIA/apg/patterns/tabs/
> Make tab labels focusable in the demo site

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSNextButton.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSPreviousButton.js
- src/context/player-context.js
Use a state variable in the state management called `playerFocusElement` to persist the focused element information when using previous/next buttons with keyboard assistance. 
This value is then used to retain focus on the previous/next buttons when the new player instance loaded on the page.
> Keep focus on next/previous buttons when using keyboard navigation

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/services/utility-helpers.js
- src/services/utility-helpers.test.js
- src/test_data/transcript-annotation.js
Default timeout value for message display is set to 3 seconds, this is overwritten by the `duration` property of the `placeholderCanvas` if it exists.
With autoplay turned on:
[autoplay_on.webm](https://github.com/samvera-labs/ramp/assets/1331659/ed3f51de-08d3-4a59-b309-5f81425faa83)
With autoplay turned off:
[autoplay_off.webm](https://github.com/samvera-labs/ramp/assets/1331659/d270c979-2d88-4a48-9065-3d7096329ec0)
> Setting restricted message timer when using autoplay

- package.json
- rollup.config.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- yarn.lock
With these changes `yarn build` and `yarn pack` succeed and there aren't any errors when I bring it into my local avalon.  It also doesn't appear to increase the size of the build much.  More testing can be done later as part of future i18n work.
Resolves #254.
> Use full relative path to lang json files and configure rollup for dynamic json imports

- src/components/Transcript/Transcript.js
- src/services/transcript-parser.js
This PR adjusts how `canvasIndex` in the state is set. The behavior with these changes is somewhat flaky. Sometimes the hooks fire on every canvas change, sometimes they don't fire at all. I would guess it has something to do with the event listener not actually getting associated with player. 
Having the event listener and the mutation observer in place at the same time I think did provide somewhat more consistent behavior in testing when switching canvases but would trigger the transcript component to enter its loading state multiple times.
@Dananji, could you do some testing and see if you can get it working consistently?
> Change canvas change trigger from a mutation observer to an event listener

- src/components/MetadataDisplay/MetadataDisplay.js
- src/components/MetadataDisplay/MetadataDisplay.md
- src/components/MetadataDisplay/MetadataDisplay.scss
- src/components/MetadataDisplay/MetadataDisplay.test.js
- src/components/Transcript/Transcript.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/test_data/playlist.js
With default props => `displayOnlyCanvasMetadata=false, displayAllMetadata=false`:
With `displayOnlyCanvasMetadata=true`:
With `displayAllMetadata=true`:
Canvas details change with autoplay:
[Canvas Details Update with Playback.webm](https://github.com/samvera-labs/ramp/assets/1331659/0414aa4f-55e4-48ef-9be7-90d65e61e472)
Usage of new props;
| Prop values  | Display in UI |
| ------------- | ------------- |
| default props  | only Manifest metadata  |
| `displayOnlyCanvasMetadata=true` with other default props  | only Canvas metadata  |
| `displayOnlyCanvasMetadata=true && displayTitle=false` with other default props  | only Canvas metadata  |
| `displayOnlyCanvasMetadata=true` with other default props  |  only Canvas metadata w/o title  |
| `displayOnlyCanvasMetadata=true && …
> Canvas metadata

- src/services/iiif-parser.test.js
- src/services/utility-helpers.js
- src/services/utility-helpers.test.js
Update the timeout value for #316
> Increase Default Timeout

- src/styles/main.scss
Fixes [Avalon #5500](https://github.com/avalonmediasystem/avalon/issues/5500)
Is this the approach we want to take for resolving that issue? I think adjusting the height in this way shouldn't have knock on effects and it isn't really a noticeable reduction unless you're specifically looking for the change. But is there a better approach?
> Reduce media height

- src/components/Transcript/Transcript.js
- src/services/utility-helpers.js
- src/services/utility-helpers.test.js
Fixes #309, Fixes #321
This PR handles the case where a ".doc" extension was being duplicated. This approach checks for an extension in the file name before checking the URL since Avalon does not include file names in the URL. It then checks if the extension it found is part of the internal list of valid extensions. If it is, we add "(machine generated)" to the filename if necessary and then rely on the browser to assign the right extension to the download. If it is not valid, we do the same processing for "(machine generated)" and then manually add ".doc" and provide that filename to the download link. This prevents the duplication we were seeing and should prevent multiple extensions in general.
This PR also includes a fix for #321 where the download button was not rendering for …
> Primarily rely on browser for file extension assignment

- src/components/Transcript/Transcript.js
- src/components/Transcript/TranscriptMenu/TranscriptDownloader.js
- src/components/Transcript/TranscriptMenu/TranscriptSelector.js
Part of https://github.com/avalonmediasystem/avalon/issues/5341 
This is a partial backport of https://github.com/samvera-labs/ramp/commit/ab51ab095c25a7a3039a9e41a8f41cc9243e4a9c although I did change the labels slightly based upon what I thought would be more readable and consistent.  If these changes are okay then we should forwardport them to `main`.
Once this is merged I can work on cutting a v1.2.2 from the new v1.2.x branch.
> Backport of Accessibility fixes for current versions of avalon

- src/components/MetadataDisplay/MetadataDisplay.js
- src/components/MetadataDisplay/MetadataDisplay.test.js
- src/test_data/empty-playlist.js
Resolves #339 
This PR addresses the specific error seen in #339 and may resolve https://github.com/avalonmediasystem/avalon/issues/5504 but I don't think that it fully allows ramp to open manifests with no canvases.  When I try to open a manifest with no canvases (playlist or normal) in the ramp demo app it hits an error boundary in iiif-parser.  It looks like this happens in ramp in avalon as well but that it logs the error and moves on.
> Add safe navigation and fallback in case there aren't any canvases in manifest

- src/components/AutoAdvanceToggle/AutoAdvanceToggle.js
- src/components/StructuredNavigation/NavUtils/ListItem.js
- src/components/StructuredNavigation/NavUtils/SectionHeading.js
- src/components/StructuredNavigation/StructuredNavigation.js
This PR covers two issues:
- https://github.com/avalonmediasystem/avalon/issues/5566
- https://github.com/avalonmediasystem/avalon/issues/5567
Additional notes are in commit messages.
> Some accessibility fixes

- package.json
I was finding this useful when debugging tests I was writing.  The `--inspect` flag to `node` sets up a debugging server on port 9229 which I connected to with Chrome using `chrome://inspect` and clicking `Open dedicated DevTools for Node`.  Then all I had to do was put in `debugger` statements in the code where I wanted them.
I'm guessing that IDEs like VSCode has some built in tools that invoke node with this flag and connect for interactive debugging within the IDE.  There may also be commandline debugging clients.   I think this script alias should expose the node inspector allowing for developers to use whichever tool they prefer.
See https://nodejs.org/en/guides/debugging-getting-started
> Provide test:debug script alias that makes it easy to debug with any dev tools

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/services/iiif-parser.test.js
- src/services/utility-helpers.js
- src/services/utility-helpers.test.js
With Avalon IIIF Manifests, Ramp receives identical captions/subtitles information from both IIIF Manifest and HLS manifest. When VideoJS in Ramp is using its normal text track handling with these IIIF Manifests, captions/subtitles get duplicated in the player's captions/subtitles menu because it uses captions/subtitles information in both manifests. 
Using VideoJS option `html5: { nativeTextTracks: true }` prevents captions/subtitles duplication for Avalon IIIF Manifests, but this hides text tracks for other IIIF Manifests where there are no HLS manifests with captions/subtitles information.
Therefore in this PR; `html5: { nativeTextTracks: true }` is removed and added a filter in the JS code to programmatically remove the duplicated captions/subtitles in the player's captions/subtitles …
> Filter duplicated captions instead of switching off native text track behavior in VideoJS

- src/components/StructuredNavigation/NavUtils/ListItem.js
- src/components/StructuredNavigation/NavUtils/ListItem.test.js
- src/components/StructuredNavigation/NavUtils/SectionHeading.test.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/test_data/playlist.js
Part of https://github.com/avalonmediasystem/avalon/issues/5581
Summary is rendered as a data attribute alongside the canvas label for playlist `ListItem`s.
In order to read the summary I had to parse the manifest again.  I'd hoped that there was a better way but couldn't find one.  Manifesto doesn't have a convenience method for getting the summary of a canvas and since it should be a language map the code to read summary is a little bit involved.
> Read canvas summary and render as data attribute alongside label

- src/components/StructuredNavigation/StructuredNavigation.js
- src/components/StructuredNavigation/StructuredNavigation.scss
This PR also adds a border around the structured nav. In testing, the `!important` css tags were necessary because the "ramp.css" file from the build (I think) was overriding the component specific file. Should the `!important` tags be removed because the CSS will compile into that file when we do another build?
> Add fade out and message to indicate scrolling of structured nav

- src/components/StructuredNavigation/StructuredNavigation.js
- src/components/StructuredNavigation/StructuredNavigation.scss
_Playlist structure_
Before:
After:
And this doesn't change the regular structure display.
Related issue: https://github.com/avalonmediasystem/avalon/issues/5589
> Add padding to playlist structure nav

- src/services/browser.js
> Use touchpoints instead of iPad regex to detect iPads

- src/components/MediaPlayer/MediaPlayer.js
- src/services/browser.js
Phones and tablets lack the ability to :hover, so the behavior of the volume slider is inconsistent and confusing on such devices. We can provide consistent behavior by disabling the slider and only providing a toggle for mute/unmute.
Resolves #352
> Disable volume slider for mobile devices

- src/styles/main.scss
We had previously disabled the transition animation for when the horizontal slider becomes active, but there was another transition that would activate when the slider returned to inactive. Overriding this transition resolves #377.
> Remove transition when horizontal volume becomes inactive

- src/components/MediaPlayer/MediaPlayer.js
This resolves the issue with playlist items being skipped (#375) and may also resolve #385. 
Playlist items were being skipped because the `handleTimeUpdate` method in `VideoJSProgress` was firing a second 'ended' event while the player was in the middle of initializing the new playlist item.  This was happening because the start time of the previous playlist item was still the `currentTime` which was greater than the end time of the initializing playlist item. Setting the `fromStart` flag when calling `initCanvas` forces the player to set current time in the state to what is specified in the manifest.  This shouldn't affect structure navigation clicks across canvases because that should be handled by the `switchCanvas` method which passes along a value for `fromStart` instead of assuming …
> Force initialization of canvas to start time specified in manifest when canvas index changes

- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
Switching our time updates to trigger on an interval caused the handler to be called continuously, even after media had ended. This resulted in undesirable behavior in the structured nav when the last item would finish. Preventing the handler from firing when the player is in the 'ended' state fixes the behavior.
> Disable time updates when media has ended

- src/components/MediaPlayer/MediaPlayer.js
With the fix in https://github.com/samvera-labs/ramp/pull/386, player's time doesn't set to the clicked structure item's start time when using structured navigation to switch between canvases.
This PR restricts the behavior in https://github.com/samvera-labs/ramp/pull/386 only to playlist manifests.
> Only force canvases to start from begining in playlist contexts

- src/components/AutoAdvanceToggle/AutoAdvanceToggle.js
Labels wrapping inputs includes a standard behavior for toggling checkboxes.  I tried to mimic this behavior with an onclick event handler for the div but then the checkbox was appearing as readOnly so react gave warnings and I assume screen readers might not think it interactive.  Because of this I tried reverting to a label and including the aria-labelledby attribute even though it appeared to possibly be problematic due to either duplicating the aria-label on the checkbox input or for referencing an element which may or may not be rendered, but SiteImprove appears to be happy with it in either case. WAVE doesn't like it when the aria-labelledby reference doesn't exist but maybe we can treat this as an edge-case now since the label is shown by default.
> Revert to label so toggling works and include aria-labelledby

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/MediaPlayer.test.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSTrackScrubber.js
- src/components/MediaPlayer/VideoJS/components/styles/VideoJSTrackScrubber.scss
Related issue: https://github.com/avalonmediasystem/avalon/issues/5624
> Show track scrubber in playlist context

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/services/iiif-parser.test.js
- src/services/utility-helpers.js
- src/services/utility-helpers.test.js
We were getting a console error about list children requiring a key. This was related to our caption tracks array. I think we were seeing this because [JSX elements in a `map()`](https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key) always require keys. Adding a key attribute to the track element within the map in VideoJS initialization resolves the error.
> Add key to track map in VideoJS initializer

- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
I was not able to track down the root cause, but not all player instances would be assigned `player.ended() === true` when we triggered the `ended` event in the time update handler. This was only seen with playlist items in my testing, but it did not seem to occur with all playlists. The `pause` event, however, does seem to be triggering consistently and assigning the proper values. When checking if we are at or past the end of the video, we can prevent continuous state updates by also checking if the player is already paused, making the assumption that this means the code within the block has already run once.
> Check if player is paused before firing ended events

- src/components/MediaPlayer/MediaPlayer.test.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/services/local-storage.js
- src/services/local-storage.test.js
Resolves #390 
This PR adds a helper service to make it easy to use localStorage as a React hook.  (It is adapted from https://blog.logrocket.com/using-localstorage-react-hooks/)  The `useLocalStorage` then gets used to store and retrieve volume and quality selections.  Volume is then set on player ready.  Quality is set by adjusting the `selected` attribute on sources right before instantiating the videojs player.  I thought keeping the storing/retrieving/setting all in the VideoJSPlayer component was simpler and kept it contained instead of trying to change the parser code to include the quality selection from localStorage.
I tried to write tests for the helper service but wasn't able to figure out how to setup the test.  I also tried adding tests of the rendered VideoJSPlayer component …
> Use localStorage to make volume and quality settings sticky

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/styles/main.scss
Text tracks were generating with an exceedingly large font in full screen portrait mode on mobile browsers. Overriding the native VideoJS styling and explicitly defining a font size remedies the issue.
> Force text track font size in mobile contexts

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
The volume sticky setting doesn't track when a user mutes/unmutes.  This PR makes muted be a sticky setting alongside the volume sticky setting.
Note there is not a specific event for muted but when a user mutes/unmutes the `volumechange` event is triggered.
#390
> Make muted be a sticky setting

- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
- src/styles/main.scss
Related issue: https://github.com/samvera-labs/ramp/issues/400
> Fix fullscreen crashing in Safari in iPad on iOS 17

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
The `sources` variable is not set when there is a blank canvas, causing an error. This breaks generation of the dummied out player instance that we rely on for certain actions within Avalon. Using the safe navigator prevents the error, allowing generation of the player to finish.
> Use safe navigator when setting quality

- src/styles/main.scss
I am not sure why the rule was not rendering in Ramp, but when loaded into Avalon there was a larger font CSS on `.vjs-text-track-cue` that was rendering. This caused the smaller font on the child div to display as if the captions were double spaced because the child font was not filling the allotted space from the parent. Setting the parent font to 0px and using solely the child font seems to fix the rendering.
> Override VJS caption font to prevent double spacing

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/test_data/playlist.js
- src/test_data/transcript-multiple-canvas.js
This PR fixes double captions in iOS devices in playlist contexts. 
The reason for the bug was that the check identifying HLS streams in Ramp failed to distinguish some playlist items as HLS streams.
Playlist items added as clips in Avalon's playlist manifests have the media URLs presented as media fragments and these doesn't end with `.m3u8` but has `#t=...` at the end to indicate the media fragment. And Ramp check expected all HLS stream URLs to end with `.m3u8` which failed.
| Captions menu in Ramp | Captions menu in iOS native player |
| :---         |     :---:      |
*Media object  manifest*
| ![screenshot-iPhone 15-17 3](https://github.com/samvera-labs/ramp/assets/1331659/3745745c-68bf-46d8-8819-f00c24f1ef37)  | ![screenshot-iPhone 15-17 …
> iOS double captions fix

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
Related issue: https://github.com/samvera-labs/ramp/issues/390
In `VideoJSPlayer` module the `VolumePanel` Video.js component is added a CSS class to make it always visible in audio players.
In mobile devices the `VolumePanel` component is replaced by `MuteToggle` and `VolumePanel` is non-existent in a mobile device context. 
So the code where the CSS class is set, was throwing an error stopping the execution of the rest of the code in the `player.ready()` function, where the sticky mute is set.
> Fix sticky mute when switching from video to audio in mobile

- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/test_data/lunchroom-manners.js
With this change metadata with null values would show up in the MetadataDisplay component as below;
This is identical to the behavior in both Clover and UV.
@joncameron Does this look okay? Or do you think removing the metadata field in the display works better?
Related issue: https://github.com/samvera-labs/ramp/issues/379
> Interpret null values in metadata as empty strings

- src/components/SupplementalFiles/SupplementalFiles.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/services/utility-helpers.js
- src/services/utility-helpers.test.js
- src/test_data/audiannotate-test.js
Related issue: https://github.com/samvera-labs/ramp/issues/346
Changes in the parser:
- Fail gracefully for empty canvases when represented with a body but no URIs in it
- Fix condition for reading `items` list under `AnnotationPage` property, handle cases when there are no `items` list
These changes are related to reading AudiAnnotate manifests in Ramp.
> Test audiannotate

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
Related issue: https://github.com/avalonmediasystem/avalon/issues/5655
This PR changes the captions filtering in the check, to always use the tracks injected by Video.js instead of using HLS tracks. 
Reason for using Video.js tracks: sometimes the HLS' tracks can have `DEFAULT=NO` which sets the captions off by default. Video.js tracks are always created with `default` set to `true` in the Ramp code, ensuring that captions are on by default.
> Change caption filtering to always use VideoJS' tracks instead of HLS tracks

- src/components/MediaPlayer/MediaPlayer.scss
In iOS versions < 14 `aspect-ratio` CSS property is not supported, and this caused the placeholder canvas message to not to display in Safari browsers.
Related issue: https://github.com/samvera-labs/ramp/issues/347
> Use alternate CSS properties to set the Canvas message height

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
Related issue: https://github.com/avalonmediasystem/avalon/issues/5681
Before:
After:
> Only display CC button for Video instances

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
In investigation for #422 I was unable to find a way to force autoplay of all items because iOS locks down that functionality as tight as they can (I am unsure why autoplay of videos works on some devices, probably something to do with them using the native player). However, I did find that certain versions of iOS triggered a runtime error within Ramp by the method of how they prevent/cancel the play event. This error catch should prevent that error from triggering the error boundary and allow users to interact regularly with the Ramp components.
> Prevent iOS rejected promise from raising error boundary

- src/services/utility-helpers.js
Related issue: https://github.com/avalonmediasystem/avalon/issues/5666
Trigger player hotkeys when focus is not on an input, textarea or on a navigation tab with the key pressed is one of left/right arrow keys. This specific combination of keys with a focused navigation tab is avoided to allow keyboard navigation between tabbed UI components, instead of triggering player hotkeys.
W3C documentation for tab keyboard navigation: https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/
> Omit active tab navigation with left/right key events in hotkeys

- public/lunchroom_manners/lunchroom_manners.srt
- public/manifests/dev/lunchroom_manners.json
- public/manifests/dev/playlist-manifest.json
- public/manifests/dev/volleyball-for-boys.json
- public/manifests/prod/lunchroom_manners.json
- src/components/Transcript/Transcript.js
- src/components/Transcript/Transcript.md
- src/components/Transcript/Transcript.test.js
- src/services/transcript-parser.js
- src/services/transcript-parser.test.js
- src/services/utility-helpers.js
- src/services/utility-helpers.test.js
Related issue: #441 
Todo: write documentation in the Wiki
> Add SRT support in Transcript component

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/services/utility-helpers.js
Related issue: https://github.com/avalonmediasystem/avalon/issues/5695
> Remove HLS caption handling

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/styles/main.scss
Related issue: #452 
On initial load programmatically select the first available caption only one caption is shown as selected in the captions menu;
Additional CSS fix to captions icon: fixed captions menu shifting down when captions are turned off;
Before:
After:
> Fix multiple captions being selected on initial load

- src/components/StructuredNavigation/NavUtils/ListItem.js
This PR fix a regression from the work done in https://github.com/samvera-labs/ramp/pull/447.
Regression: for inaccessible items all structure items are getting highlighted since there are not active items. Because of this, the check for setting active items in the styling was inaccurately evaluating the condition to be true and highlighting all the structure items as active when none of them are.
Before: 
After:
> Prevent structure items getting highlighted for inaccessible items

- src/components/IIIFPlayer/IIIFPlayer.js
- src/components/IIIFPlayer/IIIFPlayer.md
- src/components/IIIFPlayerWrapper.js
- src/components/MediaPlayer/MediaPlayer.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/services/utility-helpers.js
Related issue: https://github.com/samvera-labs/ramp/issues/457
This PR introduces a new prop called `emptyManifestMessage` for the `IIIFPlayer` component to set a custom message to display when a given IIIF Manifest has no resources (canvases) in it.
An empty playlist manifest will be displayed as follows:
in Ramp with default value for `emptyManifestMessage` prop;
in Avalon with `emptyManifestMessage='This playlist currently has no playable items.'`;
> Display a message for empty manifests without crashing

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
Before:
After:
This doesn't change the behavior but the appearance of the marker on the time rail for structure timespans that exceed the Canvas duration.
Related issue: #458
> Adjust marker display on UI when end > canvas duration

- src/components/StructuredNavigation/NavUtils/ListItem.js
- src/components/StructuredNavigation/NavUtils/ListItem.test.js
- src/components/StructuredNavigation/NavUtils/SectionHeading.test.js
This PR fixes a bug introduced in https://github.com/samvera-labs/ramp/pull/447.
This bug was released in version 3.1.0, and possibly breaks add to playlist functionality for current track option in Avalon 7.7.1.
> Build active structure item classname into a single line

- src/components/SupplementalFiles/SupplementalFiles.js
- src/components/SupplementalFiles/SupplementalFiles.md
- src/components/SupplementalFiles/SupplementalFiles.test.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/test_data/lunchroom-manners.js
- src/test_data/transcript-multiple-canvas.js
> **Need` to test with a sample manifest from Avalon once the manifest generation work is deployed to `avalon-dev`** 
✅ 
In the Ramp demo site sample;
Before:
After:
Related issue: #467
> Only display rendering files in the supplemental files component

- README.md
- package.json
- src/components/MediaPlayer/VideoJS/components/js/VideoJSFileDownload.js
- src/styles/main.scss
- yarn.lock
Merge after 3.1.0 release
Related issue: #401 
This PR upgrades Video.js to 8.10.0 and @silvermine/videojs-quality-selector to 1.3.1. 
In my testing, all of the custom components seemed to be working as I would expect on all platforms once the File Downloader component had been updated to the new format required by Video.js. 
I did encounter a change in behavior with captions on mobile devices where the text was covering the video. In Video.js 8.4.0 they implemented a [change to force text tracks to overlay the video player](https://github.com/videojs/video.js/pull/8009). Our custom CSS to override text track size resulted in the overlaid text track being too large in font so I have removed that CSS.
> Upgrade Video.js to v8.10.0

- public/manifests/dev/lunchroom_manners.json
- public/manifests/dev/playlist-manifest.json
- src/components/MetadataDisplay/MetadataDisplay.js
- src/components/MetadataDisplay/MetadataDisplay.scss
- src/components/MetadataDisplay/MetadataDisplay.test.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/test_data/lunchroom-manners.js
- src/test_data/playlist.js
- src/test_data/transcript-annotation.js
Related issue: #331 
When displaying both Manifest and Canvas metadata;
When displaying only Manifest metadata (default behavior);
When displaying only Canvas metadata (e.g. playlist page `Source Item Details` panel);
By default, adds a rights section at the end of the metadata to for Manifest to display `rights` and `requiredStatment` if one of the properties is specified.
If canvas related metadata are display is turned on via either `displayAllMetadata` or `displayOnlyCanvasMetadata` it adds a rights section to end of  metadata.
`rights` property in the IIIF Manifest is displayed with the label `License`.
> Rights metadata

- public/lunchroom_manners/lunchroom_manners.vtt
- src/components/Transcript/Transcript.js
- src/components/Transcript/Transcript.scss
- src/components/Transcript/Transcript.test.js
- src/services/transcript-parser.js
- src/services/transcript-parser.test.js
Related issue: #440 
The following WebVTT file is displayed in the transcript component with comments:
```
WEBVTT
region
id:bill
width:40%
lines:3
regionanchor:100%,100%
viewportanchor:90%,90%
scroll:up
STYLE
::cue {
background-image: linear-gradient(to bottom, dimgray, lightgray);
color: papayawhip;
}
/* Style blocks cannot use blank lines nor "dash dash greater than" */
NOTE
This file was machine-generated.
The cues and timing maybe not 100% accurate.
1
00:00:01.200 --> 00:00:21.000 region:fred align:left
[music]
NOTE End of music, and starting dialog
2
00:00:22.200 --> 00:00:26.600 region:bill align:right
<em>Just</em> before lunch one day, a puppet show 
was put on at school.
```
> Vtt parse fix

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSTrackScrubber.js
- src/services/utility-helpers.js
> Fix track scrubber bugs in Videojs re-setup work

- src/components/MetadataDisplay/MetadataDisplay.scss
> Wrap overflowing metadata text into new lines to avoid horizontal scroll

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
Always set player container's aspect-ratio to video, when displaying a blank Canvas (inaccessible item).
> Set player container aspect ratio to 16:9 for blank canvas messages

- demo/index.html
- src/components/MetadataDisplay/MetadataDisplay.js
- src/components/StructuredNavigation/NavUtils/ListItem.js
- src/services/utility-helpers.js
Found these issues via a axe scan on Ramp demo site;
- Ensures `<dt>` and `<dd>` elements are contained by a `<dl>`. Description list item does not have a `<dl>` parent element in `MetadataDisplay` component
- Ensures elements with an ARIA role that require child roles contain them. Element has children which are not allowed: li[aria-label] in the `StructuredNavigation` component
- Ensures every HTML document has a lang attribute. The <html> element does not have a lang attribute in the demo implementation page
> Accessibility fixes to issues found in axe report

- .circleci/config.yml
Found that both node version in Ramp's CircleCI orb are EOL, when came across the failing tests in #505. 
So, this PR is to uppgrade Node in Circle-CI from node 14 and 16 to 18 (EOL: April 2025 according to https://endoflife.date/nodejs) and 20.
I first tried bumping up to Node 21, which failed because of [`node-sass`](https://www.npmjs.com/package/node-sass) being deprecated.
> Update Node in Circle-CI

- src/components/StructuredNavigation/NavUtils/ListItem.js
- src/components/StructuredNavigation/NavUtils/SectionHeading.js
- src/components/StructuredNavigation/NavUtils/SectionHeading.test.js
- src/components/StructuredNavigation/StructuredNavigation.js
- src/components/StructuredNavigation/StructuredNavigation.scss
- src/components/StructuredNavigation/StructuredNavigation.test.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/test_data/multiple-canvas-auto-advance.js
- src/test_data/playlist.js
- src/test_data/single-canvas.js
- src/test_data/transcript-annotation.js
Related issue: #469 
With the changes to structure parsing structured navigation now looks as follows;
- Cookbook recipe with a single Canvas: [Table of Contents for Multiple A/V Files on a Single Canvas](https://iiif.io/api/cookbook/recipe/0064-opera-one-canvas/) and [Table of Contents for A/V Content](https://iiif.io/api/cookbook/recipe/0026-toc-opera/)
- Cookbook recipe with multiple Canvases: [Table of Contents for Multiple A/V Files on Multiple Canvases](https://iiif.io/api/cookbook/recipe/0065-opera-multiple-canvases/) 
- Avalon manifest from [avalon-dev](https://avalon-dev.dlib.indiana.edu/media_objects/fn106x94r/)
- Avalon playlist manifest from [avalon-dev](https://avalon-dev.dlib.indiana.edu/playlists/94/)
> Update structure parsing to include root-level Range in display

- src/components/MediaPlayer/VideoJS/components/js/VideoJSTrackScrubber.js
- src/services/iiif-parser.js
Fixes the following bugs;
1. Player marker filtering bug in track scrubber with the addition of transcript search hit markers on the progress bar. The player crashes when switching from a Canvas without structure to a Canvas without structure, because `currentTrackRef` variable in track scrubber component is not getting setup properly. This is a regression of the work done in #497.
2. Avoid unnecessary `console.error` message in the console when using `startCanvasId` prop without specifying a value for `startCanvasTime` prop when Ramp is initialized.
> Fix a couple of minor bugs

- public/manifests/dev/lunchroom_manners.json
- public/manifests/dev/playlist-manifest.json
- src/styles/main.scss
Fixes the following;
- resource URL of one of the canvases in the sample manifest for playlist in demo app
- remove canvas reference for first structure item in the demo manifest, since it uses the display with root range
- update CSS for thumb of the horizontal volume panel
> Fix a couple of demo data bugs

- public/manifests/dev/search-response.js
- src/components/Transcript/Transcript.js
- src/components/Transcript/Transcript.scss
- src/components/Transcript/Transcript.test.js
- src/components/Transcript/TranscriptMenu/TranscriptSearch.js
- src/components/Transcript/TranscriptMenu/TranscriptSelector.js
- src/context/manifest-context.js
- src/context/player-context.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/services/search.js
- src/services/search.test.js
- src/services/transcript-parser.js
- src/services/transcript-parser.test.js
- src/services/utility-helpers.js
- src/services/utility-helpers.test.js
- src/test_data/lunchroom-manners.js
- src/test_data/transcript-annotation.js
Related issue: #502 #508 
Please feel free to make changes as needed and then, squash and merge once again it's ready.
> Content search

- src/components/Transcript/Transcript.js
In Javascript 0 evaluates to false so a begin time of 0 skips rendering the time span by accident.  I switched the guard to check that the typeof the begin time is a number.
```
0 && true // => 0
20 && true // => true
typeof 0 // => 'number'
typeof 0 === 'number' && true // => true
```
Resolves #500
> Render time offsets for cues that begin exactly at 0

- src/services/transcript-parser.js
- src/services/transcript-parser.test.js
Fixes #499 and improves handling of NOTE comments.  Also includes spaces that were missing between lines of a cue or comment.
I removed `cleanTimedText` because I needed the new lines to flow through to `groupTimedTextLines` where I added additional handling of NOTE comments.
> Improve VTT parsing

- public/manifests/dev/lunchroom_manners.json
- public/manifests/prod/lunchroom_manners.json
- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
Related issue: #516 
Removing custom start property in the demo site manifests, since the iOS native player cannot seem to handle the custom start for the demo data. 
New issue to look at this: https://github.com/samvera-labs/ramp/issues/530
> Native player

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/MediaPlayer.test.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.scss
- src/context/manifest-context.js
Related issue: #501 
It was not possible to implement what was described in the done looks like in the ticket, as Video.js requires at least one source to build the player and its controls. And for inaccessible items the sources list is empty in the Canvas. 
Therefore this UI was implemented, by wiring the same functions the previous/next buttons use in the player controls to the buttons in the display.
When first item is inaccessible only display the next button; (and only displays previous button when last item is inaccessible)
Previous and next buttons when item is in the middle of the list;
Hides the timer display when auto-advance is turned off;
> Display previous/next buttons and timer for inaccessible canvases

- src/styles/_vars.scss
Related issue: https://github.com/avalonmediasystem/avalon/issues/5753
Transcript highlight colors were checked for WCAG AA color contrast ratio of 4.5:1
> Adjust text highlight color for contrast in transcript search

- src/components/Transcript/Transcript.js
- src/components/Transcript/TranscriptMenu/TranscriptSelector.js
- src/services/search.js
- src/services/search.test.js
- src/services/transcript-parser.js
- src/services/transcript-parser.test.js
- src/services/utility-helpers.js
Refinements to feature added in #502 
This PR includes the following refinements to content search:
- Use cached search results when switching between transcripts in the same Canvas without changing the query
- Preserve search counts when switching to a transcript where search is disabled
- Update search results counts properly when switching between transcripts
- Clear search counts when current search is cleared
- Display hit counts correctly when there are multiple hits in a single cue
- General refactoring to parts of code related to transcript component
> Adjust content search when switching between transcripts

- src/services/search.js
Related issue: #540 
Use a 5 millisecond delay in submitting the search API request when user is typing the query into the search box.
> Use a debounce timer for content search request

- src/services/transcript-parser.js
- src/services/utility-helpers.js
- src/services/utility-helpers.test.js
Related issue: #539 
SRT allows commas as decimal separators in the timestamps. e.g.
```
17
00:00:42,540 --> 00:00:45,420
We provide uncompromising quality,
```
When using content search on these transcripts in Avalon's search response is formatted as follows;
```
id: "https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p/manifest/canvas/2f75r800tsearch/0cb75a80-062e-4315-b361-144f6af7f958",
type: "Annotation",
motivation: "supplementing",
body: {
type: "TextualBody",
value: "<em>We</em> provide uncompromising quality,",
format: "text/plain",
},
target: "https://avalon-dev.dlib.indiana.edu/master_files/2f75r800t/supplemental_files/298transcripts#t=00:00:42.540,00:00:45,420"
```
The timestamps contain multiple commas, which resulted in incorrect timestamps when parsing the response.
> Fix parsing for timestamps with commas as decimal seperators

- src/services/search.js
Related issue: #540 
I removed the 5 millisecond timeout in the `setTimeout` and now it runs with a zero delay. This enables the browser to schedule these requests without immediately executing them. And it helps to avoid any unnecessary UI updates for intermediate responses.
I checked time it takes for the Ramp to process the search response (UI to updates right after this).
And I did this test for multiple transcripts in different items and I was seeing numbers less than 50 milliseconds (0.05 seconds) each time.
> Update setTimeout in the debounce

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.scss
- src/components/MediaPlayer/VideoJS/components/js/VideoJSNextButton.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSPreviousButton.js
> Fix previous/next button functionality with inaccessible item transitions

- src/components/Transcript/Transcript.js
- src/components/Transcript/Transcript.scss
- src/services/search.js
- src/services/search.test.js
- src/services/transcript-parser.js
- src/services/utility-helpers.js
Related issue: #513 
This PR adds the ability to see focused search hits using results navigation when there are multiple hits within a focused cue.
Example of search results navigation when the transcript is one block of text:
> Text search nav

- src/components/MediaPlayer/MediaPlayer.test.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/StructuredNavigation/StructuredNavigation.test.js
- src/services/iiif-parser.test.js
- src/test_data/playlist.js
> Do not display timer when last item is inaccessible

- src/styles/main.scss
> Small tweak to top margin of horizontal volume slider thumb

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.scss
- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
- src/context/manifest-context.js
> Fix grey overlay bug and related bugs in playlist item transitions

- src/services/search.js
- src/services/search.test.js
- src/services/transcript-parser.js
- src/services/transcript-parser.test.js
> Fix regex to identify matches in content search response

- package.json
- src/components/Transcript/Transcript.js
- src/components/Transcript/TranscriptMenu/TranscriptSearch.js
- src/components/Transcript/TranscriptMenu/TranscriptSearch.test.js
- src/services/search.js
- src/services/search.test.js
- yarn.lock
I was able to reduce the UI update time by ~2 seconds (~4 seconds to ~1 second) for search within functionality from the fixes made in this PR. 
I think this could be further improved by restricting the updates to props that goes into `TranscriptList` component with search within, maybe?
> Fix slow search by handling timing of updates and cache

- src/services/search.js
Check existence of `manifestState` context in the `search.js` when trying to parse the search service from the given Manifest.
Without this check the transcript component crashes when used outside of the context providers.
> Check if manfiestState exists for search service parsing

- src/components/MediaPlayer/VideoJS/components/styles/VideoJSFileDownload.scss
Related issue: https://github.com/avalonmediasystem/avalon/issues/5927
Once this is brought into Avalon we probably could undo the changes in https://github.com/avalonmediasystem/avalon/pull/5921 as this takes care of the misalignment of svg icons in Ramp.
> Change vertical-align CSS for SVG

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
I was still seeing the shortened progressbar on initial load in the Ramp demo site (#567) in Firefox. It seems on the initial load of the page it's safer to read the duration from options passed into the `VideoJSProgress` component rather than relying on `canvasDuration` property of the player instance.
> Read duration from either options or player property in progressbar

- src/components/StructuredNavigation/NavUtils/ListItem.js
This fixes an error I was seeing with an item in staging but not in production.  Without this fix ramp crashes before fully loading with `TypeError: k.current is null`
https://mco-staging.dlib.indiana.edu/media_objects/dj52wp041/manifest.json
> Only reset isClicked if active structure item is set

- src/components/StructuredNavigation/StructuredNavigation.scss
> Vertical align lock icon for restricted struct items

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/StructuredNavigation/StructuredNavigation.js
Related issue: #580 
Fixed behavior in PR:
- If the user has started playback at some point play the next item after an inaccessible item when the timer ends
- If the user has not started playback at any point/started playback and paused it before reaching the inaccessible item don't play the next item after an inaccessible item when the timer ends
**Not sure whether this can go into 7.8, needs to discuss before merging**
> After an inaccessible item play the next item if user has started playback

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
Related issue: #567 
It seems the fixes put in earlier were not working. This PR changes path the duration is carried over to VideoJSProgress component, which seems to be the most stable.
> Set accurate duration on progress bar creation

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
- src/components/MediaPlayer/VideoJS/components/styles/VideoJSProgress.scss
Related issue: #560 
~~**Merge this after 7.8 related Ramp release is created**~~
After some discussion in Slack it was decided to merge this for 7.8 release since this has similar scope as #580 which is going to be in 7.8.
> Update variables in progress component to refs to maintain accuracy with canvas updates

- src/styles/main.scss
Related issue: #586 
~~**Wait for 7.8 Ramp release to be merged**~~
Before:
After:
> Align CC btn in control bar with green border

- src/components/MediaPlayer/VideoJS/components/styles/VideoJSTrackScrubber.scss
Fix marker alignment issue introduced in https://github.com/samvera-labs/ramp/pull/587
Before:
After:
> Align structure highlight marker with hovered progress bar

- src/components/IIIFPlayerWrapper.js
This commit is to fix an issue found with Ramp embedded in Avalon. If the request url from Avalon has params on the end, Avalon feeds the entire url into Ramp as
`https://example.com/endpoint?params/manifest.json`. This causes media to fail to load because it is not a valid manifest url. By removing the params from the middle of the url, we can get Ramp to request the proper manifest url.
Related issue: #615
> Sanitize manifest url if params included in middle

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/styles/main.scss
Related issue: #434  
Before:
After:
The error displays on a dismiss-able modal, without breaking the player. Once the modal is closed the user is able to select a different source from the quality selector menu.
> Display Video.js errors instead letting the player crash

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
Reveal player on `progress` event as the browser has enough data to start playback at this point.
I tested this on different browsers on different platforms for an [item from MCO](https://media.dlib.indiana.edu/media_objects/qj72p820d);
- Safari on iPhone: fires `progress` event first, and `loadedmetadata` event fires within ~10ms after that
- Safari on iPads and desktop: fires `loadedmetadata` event first, and the `progress` event fires within less than ~300ms of it
- Chrome on Android: fires `progress` event first, and `loadedmetadata` event fires within less than ~500ms (0.5sec) of it
- Firefox and Chrome on desktop: fires `progress` event first, and `loadedmetadata` event fires within less than ~1000ms (1sec) of it
Since the order in which the events are fired is different on …
> Reveal player early on progress event with enough data for playback

- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
When mouse pointer is hovering over the blocked parts of the progress-bar, the time tool-tip is displayed outside of the progress-bar container.
This PR fixes the alignment of the time tool-tip by limiting the calculated offset to always align tool-tip with the playable range of the media.
Before:
After:
> Limit time tooltip display offset to playable range width

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
> Fix player replaying last section/single section item in a loop

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/MediaPlayer.test.js
Instead of using the `hlsOptions` property to pass the credentials flag down to VideoJS, set `withCredentials: true` on each of the sources.
> Make `withCredentials` work with videojs 7.x and 8.x

- .circleci/config.yml
- package.json
- yarn.lock
Upgrading node in CicleCI to add latest Node version (22.8.0) and remove support for Node 18.
Related: https://github.com/samvera-labs/ramp/pull/640#issuecomment-2356057640
> Remove node-18 and add node-22 to CircleCI

- src/components/AutoAdvanceToggle/AutoAdvanceToggle.js
- src/components/MarkersDisplay/MarkersDisplay.js
- src/components/MarkersDisplay/MarkersDisplay.test.js
- src/components/MetadataDisplay/MetadataDisplay.js
- src/components/SupplementalFiles/SupplementalFiles.js
- src/services/ramp-hooks.js
- styleguide.config.js
Related issue: #630 
Refactor `MetadataDisplay` component's calculated UI portions to re-render only when relevant state variables are changed using `React.useMemo` hook.
Use the same concept in other mostly static components refactored in https://github.com/samvera-labs/ramp/pull/640, instead of wrapping the component export in `React.useMemo`. 
The implementation in https://github.com/samvera-labs/ramp/pull/640 with `React.useMemo` was still emitting a warning react-styleguidist docs regardless of the styleguidist config changes. And with this implementation we can still limit the re-renders to the entire component and export pure components for react-styleguidist to use to generate documents.
> Remove useMemo in component export, refactor MetadataDisplay component

- demo/app.js
- src/components/Transcript/Transcript.js
- src/components/Transcript/Transcript.md
- src/services/ramp-hooks.js
Related issue: #630 
This work moves state management in Transcript component to a custom hook.
Since `Transcript` component is built as an independent component from global state management using context providers it doesn't have the issue other components have with unnecessary re-renders.
But it can be used within context providers, without breaking its independent nature.
This refactor helps up to make use of the global state IF the component is wrapped inside the context providers.
One advantage of this is, `Transcript` component doesn't need to spin up a unnecessary JS interval to read the player instance from the page when the player is available via context providers, while still supporting its independent implementation.
> Custom hook for state management in Transcript component

- src/components/MarkersDisplay/MarkerUtils/CreateMarker.js
- src/components/MarkersDisplay/MarkerUtils/CreateMarker.test.js
- src/components/MarkersDisplay/MarkerUtils/MarkerRow.js
- src/components/MarkersDisplay/MarkersDisplay.test.js
- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/MediaPlayer.test.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSTrackScrubber.js
- src/components/MediaPlayer/VideoJS/components/styles/VideoJSTrackScrubber.scss
- src/context/manifest-context.js
- src/services/ramp-hooks.js
- src/services/ramp-hooks.test.js
- src/test_data/multi-source-manifest.js
Related issue: #630 
Includes custom hook implementations for player related state updates.
For some of the functionality in the custom hooks, unit tests are added. Most of the code in these hooks are covered by the unit tests in respective components' test-cases. Test coverage in the new module `@Services/ramp-hooks.js` added in this work (#630) is around 70%. The parts that are not covered in tests are either impossible/hard to write tests with just the custom hook functionality.
> Custom hook for MediaPlayer and VideoJSPlayer handling

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSNextButton.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSPreviousButton.js
- src/components/MediaPlayer/VideoJS/videojs-theme.scss
- src/context/player-context.js
- src/services/ramp-hooks.js
This PR includes the following;
1. Cleanup of `playerFocusElement` global state variable, as this is not needed anymore to retain focus for previous/next button keyboard navigation with the changes done on these custom components with new implementation
2. Remove `float: inline-end` styling with `display: inline-block` for player controls to right align some of the controls in the player, as this reverses the tab order of the controls when using keyboard navigation. Replace this styling to use `display: flex`
3. Fix a bug in the state updates for persisting the player's play/pause status as `isPlaying` in global state with hotkey implementation and pointer events
4. Set aspect ratio for inaccessible message display as 16/9 (equivalent to video player) when switching from an audio item to …
> Fix minor bugs in player introduced in refactor/cleanup work

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/videojs-theme.scss
- src/styles/main.scss
Related issue: #657 
This PR includes the following changes;
1. Revert volume bar to the previous state where video players have vertical volume control and audio players have sticky horizontal volume control as follows.
2. Move all popup menus above the progress-control. As part of this work display of the popup menus on `hover` event on the buttons are removed. This seems to be the common practice in other platforms e.g. LinkedInLearning and YouTube.
> Replace volume control with muteToggle/volumePanel, popup menus above progress-bar

- src/components/MediaPlayer/VideoJS/videojs-theme.scss
> Adjust progress-bar spacing to display menus above it

- src/components/MediaPlayer/MediaPlayer.test.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/services/ramp-hooks.js
Display specific error message without crashing Ramp when an empty Manifest is provided. This is a regression introduced in the refactor/upgrade work after 3.2.1 release.
> Regression bug: display error for empty Manifest w/o crashing

- src/components/StructuredNavigation/StructuredNavigation.js
- src/components/StructuredNavigation/StructuredNavigation.md
- src/components/StructuredNavigation/StructuredNavigation.scss
This PR changes the UI of the structured navigation component to include collapse/expand all sections button as part of the structures in the display. This helps to mimic the collapse/expand all button we had in Avalon in the previous implementation as below;
Before:
After:
For non-collapsible structures:
> Change UI for structured nav to include collapse all button

- src/services/ramp-hooks.js
Related issue: #673 
Only invoke `createDisplayTimeInterval()` method within `useShowInaccessibleMessage` custom hook. When this was called within `initCanvas()` in `useSetupPlayer` hook, it creates multiple intervals disabling the remaining time updates in the timer on display.
Use `canvasIndex` instead of `canvasIndexRef` in the dispatch to update manifest-state when timer ends. 
It was observed that, in Safari and Chrome using `canvasIndexRef` causes to skip an item when auto-advancing (most probably due to timing of these updates are getting overlapped) in avalon's playlists where there are inaccessible items. However this was not seen in these browsers in the demo site.
> Create inaccessible message interval only in a single custom hook

- src/components/MediaPlayer/VideoJS/components/js/VideoJSTrackScrubber.js
- src/components/StructuredNavigation/NavUtils/List.js
- src/components/StructuredNavigation/NavUtils/ListItem.js
- src/components/StructuredNavigation/NavUtils/SectionHeading.js
- src/components/StructuredNavigation/StructuredNavigation.scss
- src/components/Transcript/Transcript.js
Related issue: #622 and other a11y issues in components
> Fix a11y issues found with Siteimprove, WAVE, and Axe

- src/components/StructuredNavigation/StructuredNavigation.js
- src/components/StructuredNavigation/StructuredNavigation.md
- src/components/StructuredNavigation/StructuredNavigation.scss
This includes the following fix for non-collapsible structures when sections portion of the `StructuredNavigation` component is turned on. This mimics the previous UI for sections in Avalon for non-collapsible structures.
Before:
After:
> Fix sections UI for non-collapsible structures

- src/components/StructuredNavigation/NavUtils/List.test.js
- src/components/StructuredNavigation/NavUtils/ListItem.js
- src/components/StructuredNavigation/NavUtils/ListItem.test.js
- src/components/StructuredNavigation/NavUtils/SectionHeading.js
- src/components/StructuredNavigation/NavUtils/SectionHeading.test.js
- src/components/StructuredNavigation/StructuredNavigation.scss
- src/components/StructuredNavigation/StructuredNavigation.test.js
Related issue: #675 
Section headings:
Before: 
After: 
Child structure items:
Before:
After:
> Wrap long labels w/o spaces in structure to new lines

- src/components/MediaPlayer/VideoJS/videojs-theme.scss
> Center align progressbar in audio, and add padding

- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
When hovering over a search marker on the progress-bar the timetool-tip appears at 0:00 time-point instead of at the correct offset above the search marker
Before:
After:
> Show timetool-tip above search marker when hovering

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
Related issue: #694 
Extend `player.load()` for all Safari and iOS browsers, to make the player ready before playback starts. This allows the user to use structured navigation to seek the player to the start time of a track and start playback from there.
https://github.com/user-attachments/assets/ddb23445-de9b-4b9d-82e8-10b281b56332
> Force player to load in Safari and iOS browsers

- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
Related issue: #677 
Partial solution for this issue in #707.
This PR updates the progress-bar's played range CSS in the VideoJS player to reflect the time updates made in the native player with seek/scrub actions, when the user exits the native iOS player.
> Update progress-bar CSS on fullscreen exit in iOS

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
> Call player.load() in Safari/iOS browsers before calling play()

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/videojs-theme.scss
- src/services/ramp-hooks.js
Related issue: #687
Use control-bar width to add space on either side of the progress-bar in between the player borders and progress-bar. The previous implementation used only CSS by adjusting the width of the progress-bar which was not responding well to player resize.
> Use control-bar width to add padding to progress-bar on sides

- src/components/MediaPlayer/VideoJS/components/styles/VideoJSProgress.scss
> Remove progress-bar shadow on focus

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/components/js/VideoJSProgress.js
Related issue: #672 
When end time equals to duration Safari doesn't emit the `ended` player while other browsers do. Therefore extending the condition to include the cases where end == duration.
Test example manifest: https://avalon-dev.dlib.indiana.edu/playlists/5/manifest auto-advance from 98th item to next.
> Trigger ended event when end = duration

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
Related issue: #717 
This is a known issue in the quality-selector plugin we are using. The solution in this PR is to add back in the remote text tracks on quality selection.
> Add back tracks upon quality selection

- src/components/StructuredNavigation/NavUtils/List.test.js
- src/components/StructuredNavigation/NavUtils/SectionHeading.js
- src/services/ramp-hooks.js
Related issue: #645 
Update collapse/expand all button when each section is changed manually:
https://github.com/user-attachments/assets/f66ec740-b8c2-47f1-9eaf-e1856be08053
Expand current section when playback status changes for it:
https://github.com/user-attachments/assets/7b455d27-6291-4517-b235-482b91e857d3
> Fix collapse/expand all button behavior with each section status change

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
When switching between canvases the fragment markers do not get reset when player is paused. This creates overflowing fragment markers for the progress-bar. This was introduced when `setIsReady(true)` was moved from `loadedmetadata` event to `loadeddata` event to update playlist markers in Safari browsers (related PR: https://github.com/samvera-labs/ramp/pull/726).
Example: Load second section of https://avalon-dev.dlib.indiana.edu/media_objects/3j3332278
> Invoke handleTimeupdate to update markers on player reload

- src/components/MediaPlayer/VideoJS/components/styles/VideoJSProgress.scss
- src/components/MediaPlayer/VideoJS/videojs-theme.scss
> Remove space between control-bar pseudo elements, to mouse display on hover

- src/services/ramp-hooks.js
Related issue: #723 
**Merge after 3.3.0 tag is created**
> Use resize event on window.visualViewport to adjust control-bar width for mobile devices

- src/components/Transcript/Transcript.test.js
- src/services/transcript-parser.js
- src/services/transcript-parser.test.js
- src/services/utility-helpers.js
- src/test_data/multi-source-manifest.js
> Fix annotation parsing for Aviary annotations

- src/components/MediaPlayer/MediaPlayer.js
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/MediaPlayer/VideoJS/videojs-theme.scss
- src/context/manifest-context.js
Related issue: #710 
The error message was displaying the in player, but it had a grey overlay on top of it without letting the user access the error message modal. This is because the error message was created by VideoJS instead of the override we've implemented in Ramp.
The fix in this PR catches `player.error()` in the `player.ready()` event handler and trigger the custom event handler for player errors. When there is only one source for the Canvas and VideoJS is facing issues playing it, the error display modal dialog is shown as non-dismiss-able modal by setting the following option for VideoJS;
```
errorDisplay: {
uncloseable: sources?.length > 1 ? false : true,
}, ...
```
In addition to that, this PR adds a check in `manifest-context.js` for playlist manifests before trying to read …
> Fix error message display and general parsing error for AVAnnotate manifests

- src/components/StructuredNavigation/StructuredNavigation.test.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/test_data/transcript-multiple-canvas.js
> Avoid parsing structure ranges with 'behavior=thumbnail-nav'

- src/components/MediaPlayer/MediaPlayer.js
Related issue: #727 
Before:
After:
Device tested: iPad Pro 12.9 on iOS 17.1 in BrowserStack
> Turn on nativeTextTracks only for browsers using native iOS player

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
> Fix seeked time reset on player load in Safari

- demo/index.html
- src/components/MarkersDisplay/MarkersDisplay.scss
- src/components/StructuredNavigation/StructuredNavigation.scss
- src/components/SupplementalFiles/SupplementalFiles.scss
- src/components/Transcript/Transcript.scss
- src/styles/_vars.scss
- src/styles/main.scss
> Set font-size CSS in metadata display component and cleanup

- src/components/MediaPlayer/MediaPlayer.js
Fix a bug introduced in https://github.com/samvera-labs/ramp/pull/742.
Enable close button in error display in the player, when there are multiple canvases.
> Enable error close button for multiple canvas manifests

- src/services/annotation-parser.test.js
- src/services/annotations-parser.js
- src/services/ramp-hooks.js
- src/services/transcript-parser.js
- src/services/transcript-parser.test.js
This is not specifically related to parsing multiple TextualBody annotations, as this was covered in the work done in #431.
The changes in this PR converts the data parsed from any linked annotation resource which is not an AnnotationPage into the same data format expected in annotations.
Ramp parses these annotations into a very simple data format, which only has start time, end time, and text to be used in the Transcript component.
Related issue: #436
> Convert data from linked annotations to the same data format

- src/services/transcript-parser.js
- src/services/transcript-parser.test.js
Related issue: #750 
For the following WebVTT file the display looks as follows;
```
1
00:00:01.200 --> 00:00:21.000 region:fred align:left
[music]
NOTE End of music, and starting dialog
2
00:00:22.200 --> 00:00:26.600 region:bill align:right
<em>Just</em> before lunch one day, a puppet show 
was put on at school.
3
00:00:26.700 --> 00:00:31.500 region:fred align:left
It was called "Mister Bungle Goes to Lunch".
4
00:00:31.600 --> 00:00:34.500
It was fun to watch.
5
00:00:36.100 --> 00:00:41.300
In the puppet show, Mr. Bungle came to the 
boys' room on his way to lunch.
6
00:00:41.400 --> 00:00:46.200
He looked at his hands. His hands were dirty 
and his hair was messy.
7
00:00:46.300 --> 00:00:51.100
But Mr. Bungle didn't stop to wash his hands 
or comb his hair.
```
| Before  | After | …
> Display line breaks within a cue for WebVTT and SRT transcripts

- src/services/ramp-hooks.js
When switching manifests in demo site using `Set Manifest` form, the player instance is set to null momentarily. During this window `player.trigger('resize')` is getting called because, the resize event on window is fired when the component tree is cleared when manifest URL in the `Set Manifest` form is emptied or changed.
Adding this check prevents the code from trying to emit the 'resize' event on a null instance of the player causing the page to crash. However this doesn't break the resize functionality, as this function is called again when player instance is properly set.
> Check player is not null before player.trigger('resize') event

- src/components/MarkersDisplay/Annotations/AnnotationsDisplay.js
- src/services/annotation-parser.test.js
- src/services/annotations-parser.js
- Add support for parsing and displaying Aviary style annotations: 
- display label/value pairs from the annotation body
- combine and display multiple annotations for a single time-point as one annotation
- Filter the linked annotation resources in the Canvas to only display time-synced annotations
Related issue: #649
> Display Aviary annotations and filter linked annotations

- src/components/MarkersDisplay/Annotations/AnnotationLayerSelect.js
- src/components/MarkersDisplay/Annotations/AnnotationLayerSelect.test.js
- src/components/MarkersDisplay/Annotations/AnnotationRow.js
- src/components/MarkersDisplay/Annotations/AnnotationRow.test.js
- src/components/MarkersDisplay/Annotations/AnnotationsDisplay.js
- src/components/MarkersDisplay/Annotations/AnnotationsDisplay.test.js
- src/components/MarkersDisplay/MarkersDisplay.scss
- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/services/annotation-parser.test.js
- src/services/annotations-parser.js
- src/services/ramp-hooks.js
- src/services/ramp-hooks.test.js
- src/services/utility-helpers.js
Related issue: #649 
This PR includes the following;
- Checkbox in the annotations component to allow auto-scrolling of annotations with playback
- this is turned on by default (similar to transcripts)
- when auto-scrolling is turned on the annotation with the closest start time to the current time of the player is scrolled to the top of the annotations component and highlighted until the current time of the player reaches the next annotation in the list
https://github.com/user-attachments/assets/fb9146ad-4bb7-4fd3-acff-f9f6fd79f509
- `Show more`/`Show less` button to expand the full text of the annotation when the annotation has more than 6 lines
https://github.com/user-attachments/assets/7ae359da-a980-4079-9bd9-c544d0aa7de3
- Unit tests for all the new user interfaces
- Filter …
> Annotations functionalities

- src/components/MarkersDisplay/Annotations/AnnotationRow.js
- src/components/MarkersDisplay/Annotations/AnnotationRow.test.js
- src/components/MarkersDisplay/MarkersDisplay.scss
> Handle click on a link in annotation: open URL in same tab without seeking player

- src/components/Transcript/Transcript.js
- src/services/search.js
Fix bug around transcript search when there are notes in the transcripts and not displayed in the UI with `showNotes=false` prop. 
When feeding transcript cues to the search module use the value of `showNotes` prop to filter the transcript cues accordingly.
> Use showNotes prop in transcript search to filter

- src/components/MediaPlayer/VideoJS/VideoJSPlayer.js
- src/components/StructuredNavigation/NavUtils/List.test.js
- src/components/StructuredNavigation/NavUtils/ListItem.js
- src/components/StructuredNavigation/NavUtils/ListItem.test.js
- src/components/StructuredNavigation/NavUtils/SectionHeading.js
- src/components/StructuredNavigation/NavUtils/SectionHeading.test.js
- src/components/StructuredNavigation/StructuredNavigation.js
- src/components/StructuredNavigation/StructuredNavigation.scss
- src/context/player-context.js
- src/services/iiif-parser.js
- src/services/iiif-parser.test.js
- src/services/ramp-hooks.js
- src/services/ramp-hooks.test.js
Related issue: #779 
To test nested timespans in Ramp demo site use the example Manifest at: https://gist.githubusercontent.com/Dananji/6575bff0213ca42af36009650fa986de/raw/857c759675c84acabe900f35838295613e369bb8/nested-timespans.json
| Before  | After fix |
| ------------- | ------------- |
| <img width="901" alt="Image" src="https://github.com/user-attachments/assets/ceeac1d2-2f53-46f0-9aa8-ce431782f669" /> | <img width="901" alt="Image" src="https://github.com/user-attachments/assets/26ed2313-f153-4af3-a763-a2873fee10e1" /> |
> Show time rail highlight for current timespan when nested

- src/components/MarkersDisplay/MarkersDisplay.scss
- src/components/Transcript/Transcript.scss
- src/styles/_vars.scss
Related issue: #764 and https://github.com/samvera-labs/ramp/issues/764#issuecomment-2749402131
> Use a lighter color for active cues and annotation rows to fix contrast

- src/components/MarkersDisplay/Annotations/AnnotationRow.js
- src/components/MarkersDisplay/Annotations/AnnotationRow.test.js
- src/services/ramp-hooks.js
- src/services/utility-helpers.js
- src/services/utility-helpers.test.js
Related issue: #790 
In addition to the fix the PR includes cleanup of `useEffect` hooks in `AnnotationRow` component. There's a bunch of `useEffect` code in the component, which were moved into a custom hook as a result.
> Truncate only text nodes without counting HTML markup, cleanup useEffects

- src/services/ramp-hooks.js
- src/services/ramp-hooks.test.js
Related issue: #789 
Assumption: for time point annotations consider an implicit time range spanning from its given start time to the start time of the next annotation in the list. Therefore marking a time point annotation as active until the current time of the player reaches the start time of the next annotation's start time.
> Auto scroll time-point annotations by comparing start time avoiding end times

- src/components/MarkersDisplay/Annotations/AnnotationRow.js
- src/components/MarkersDisplay/Annotations/AnnotationSetSelect.js
- src/components/MarkersDisplay/Annotations/AnnotationsDisplay.js
- src/components/MarkersDisplay/MarkersDisplay.scss
- src/services/annotation-parser.test.js
- src/services/annotations-parser.js
- src/services/utility-helpers.js
Related issues: #811 and #815
To fix the role relationship error in annotations component, `<ul />` and `<li />` elements replaced with `<div />` elements when creating the annotations list. Because these list elements are document structure elements, implicit roles were being added to the DOM. And these roles were blocking the use of `role="button"` for annotations and displaying links and buttons within the annotation text.
As a result of this, #815 gets automatically fixed because, removing `<li>` in the annotation row implementation eliminated the list-based role overriding `role="button"` for a clickable annotation row, which automatically enables the instructions to activate the annotation in VoiceOver 
Additionally;
- added `aria-label` to annotation row with more user friendly …
> Fix voiceover and role relationship errors for annotations

- src/components/StructuredNavigation/StructuredNavigation.js
While testing the code for 4.0.0 release, I noticed that playlists structure scroll to the item that has the lowest start time on page load, even though the player shows the first item on the page. Example: https://avalon-dev.dlib.indiana.edu/playlists/5, the structure scrolls to the playlist item at the 98th position even though the player is still on the first item.
This was a bug introduced in the work that was done to fix the display of overlapping timespans in the player.
> Bug fix: keep original order of timespans for playlist

- src/components/Annotations/OtherAnnotations/AnnotationRow.js
- src/components/Transcript/Transcript.js
Related issue: #815 
Since the cues in the `Transcript` component follows the same pattern for setting the accessible labels as the `Annotation` component, I took the time to review how the accessible labels in `Transcript` component are displayed and understood by the accessibility software as a part of this work. 
As a result, I identified an issue where the accessible label not matching with the visual text of the element. So, this PR includes a small code change in the `Transcript` component related to this issue.
This issue is related to the Avalon 8.1 release.
> Fix voiceover and a11y for cues in transcripts & annotations
